# Defaults
spec:
  destination:
    server: https://kubernetes.default.svc
cluster:
  name: "in-cluster"
  awsRegion: "ap-southeast-2"
  clusterAutoscaler:
    namespace: "kube-system"

crossplane:
  packageCache:
    sizeLimit: 100Mi
  args:
    - --debug
  providers:
    - package: crossplane/provider-sql-controller:master    