apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  labels:
    app: kiali-operator
spec:
  deployment:
    accessible_namespaces:
      - "**"
  istio_namespace: istio-system
  auth:
    strategy: anonymous
  external_services:
    prometheus:
      url: "http://prometheus-kube-prometheus-prometheus.prometheus:9090"
    tracing:
      in_cluster_url: "http://jaeger-tracing-query.jaeger:16686"
      url: "http://jaeger.{{ .Values.dns.fqdn }}"
      use_grpc: false
