---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}-svc-stable"
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: "{{ .Values.app.name }}-rollout"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}-svc-canary"
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: "{{ .Values.app.name }}-rollout"
