# Defaults
spec:
  destination:
    server: https://kubernetes.default.svc
cluster:
  name: "in-cluster"
  awsRegion: "ap-southeast-2"
  clusterAutoscaler:
    namespace: "kube-system"

# Must be provided
argocd: 
  namespace: ""
apps:
  repoURL: ""
  path: ""
  targetRevision: ""
dns: 
  fqdn: ""
  externalDNS:
    enabled: false
    zoneID: ""
    aws: 
      serviceAccountName: ""
tls:
  certManager:
    enabled: true
    email: ""
    aws: 
      serviceAccountName: ""
    selfSigned: 
      enabled: true
    letsEncryptStaging:
      enabled: false
    letsEncryptProduction:
      enabled: false
secrets:
  externalSecrets:
    enabled: false
    aws:
      secretsManager:
        serviceAccountName: ""
