# jk8s Values
jk8s:
  argocd: 
    namespace: {{ .Release.Namespace }}
  apps:
    repoURL: https://github.com/jdotw/jk8s.git
    path: applications
    targetRevision: HEAD
  dns: 
    fqdn: "example.jk8s.io" # Required
    externalDNS:
      enabled: false
      zoneID: ""
      aws: 
        serviceAccountName: ""
  tls:
    certManager:
      enabled: true
      email: cert@jk8s.io
      selfSigned: 
        enabled: true
      letsEncryptStaging:
        enabled: false
        aws: 
          serviceAccountName: ""
      letsEncryptProduction:
        enabled: false
        aws: 
          serviceAccountName: ""
  secrets:
    externalSecrets:
      enabled: false
      aws:
        secretsManager:
          serviceAccountName: ""


# Dependency Chart Values
argo-cd:
  controller:
    metrics:
      enabled: true
  dex:
    metrics:
      enabled: true
  server:
    metrics:
      enabled: true
    extraArgs:
      - --insecure
  redis:
    metrics:
      enabled: true
  repoServer:
    metrics:
      enabled: true

