# Defaults
spec:
  destination:
    server: https://kubernetes.default.svc
cluster:
  name: "in-cluster"
  awsRegion: "ap-southeast-2"
  clusterAutoscaler:
    namespace: "kube-system"

# CertManager
letsEncrypt:
  staging:
    enabled: false
    email: ""
    route53:
      zoneID: ""
  production:
    enabled: false
    email: ""
    route53:
      zoneID: ""


# Dependencies
cert-manager:
  installCRDs: true
  serviceAccount:
    create: true
    name: cert-manager
  securityContext:
    fsGroup: 1001
