{{ if .Values.aws.secretsManager.argocdServiceAccountName }}
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secrets-store-aws-sm
  namespace: {{ .Values.argocd.namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: "ap-southeast-2"
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.aws.secretsManager.argocdServiceAccountName }}
{{ end }}
{{ if .Values.aws.secretsManager.telemetryServiceAccountName }}
---            
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secrets-store-aws-sm
  namespace: telemetry
spec:
  provider:
    aws:
      service: SecretsManager
      region: "ap-southeast-2"
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.aws.secretsManager.telemetryServiceAccountName }}
{{ end }}
{{ if .Values.aws.secretsManager.appServiceAccountName }}
---            
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secrets-store-aws-sm
  namespace: app
spec:
  provider:
    aws:
      service: SecretsManager
      region: "ap-southeast-2"
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.aws.secretsManager.appServiceAccountName }}
{{ end }}
{{ if .Values.aws.secretsManager.crossplaneServiceAccountName }}
---            
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secrets-store-aws-sm
  namespace: crossplane-system
spec:
  provider:
    aws:
      service: SecretsManager
      region: "ap-southeast-2"
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.aws.secretsManager.crossplaneServiceAccountName }}
{{ end }}