{{ if .Values.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: rds-secret-crossplane
  namespace: crossplane-system
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: secrets-store-aws-sm
    kind: SecretStore
  target:
    name: rds
    creationPolicy: Owner
    template:
      data:
        # For use by crossplane sql-provider
        endpoint: "{{ "{{ .host | toString }}" }}"
        port: "{{ "{{ .port | toString }}" }} "
        username: "{{ "{{ .username | toString }}" }}"
        password: "{{ "{{ .password | toString }}" }}"
  dataFrom:
    - key: "{{ .Values.rdsSecretName }}"
{{ end }}