{{ if .Values.letsEncrypt.staging.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "{{ .Values.letsEncrypt.staging.email }}"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    {{ if .Values.letsEncrypt.staging.route53.zoneID }}
    - dns01:
        route53:
          region: us-east-1
          hostedZoneID: "{{ .Values.letsEncrypt.staging.route53.zoneID }}"
    {{ end }}
{{ end }}