apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: integration-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "{{ .Values.apps.repoURL }}"
    targetRevision: "{{ .Values.apps.targetRevision }}"
    path: "{{ .Values.apps.path }}/integration-app"
    helm:
      parameters:
        # external-secrets
        - name: externalSecrets.aws.secretsManager.serviceAccountName
          value: "{{ .Values.secrets.externalSecrets.aws.secretsManager.serviceAccountName }}"
        # cert-manager
        - name: certManager.letsEncrypt.staging.enabled
          value: "{{ .Values.tls.certManager.letsEncrypt.staging.enabled }}"
        - name: certManager.letsEncrypt.staging.email
          value: "{{ .Values.tls.certManager.letsEncrypt.staging.email }}"
        - name: certManager.letsEncrypt.staging.route53.zoneID
          value: "{{ .Values.tls.certManager.letsEncrypt.staging.route53.zoneID }}"
        - name: certManager.letsEncrypt.production.enabled
          value: "{{ .Values.tls.certManager.letsEncrypt.production.enabled }}"
        - name: certManager.letsEncrypt.production.email
          value: "{{ .Values.tls.certManager.letsEncrypt.production.email }}"
        - name: certManager.letsEncrypt.production.route53.zoneID
          value: "{{ .Values.tls.certManager.letsEncrypt.production.route53.zoneID }}"

  destination:
    namespace: "{{ .Values.argocd.namespace }}"
    server: "{{ .Values.spec.destination.server }}"

  syncPolicy:
    automated:
      prune: true
