---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-app
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.apps.repoURL }}
    targetRevision: {{ .Values.apps.targetRevision }}
    path: "{{ .Values.apps.path }}/istio-app"

  destination:
    namespace: istio-system
    server: "{{ .Values.spec.destination.server }}"

  syncPolicy:
    automated:
      prune: true
