---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: amazon-route53-zone
  labels:
    provider: aws
    service: route53
    compute: managed
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: route53.jk8s.io/v1beta1
    kind: RDSCluster

  patchSets:
    - name: common-parameters
      patches:
        - fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.region"

  resources:
    - name: dbzone
      base:
        apiVersion: route53.aws.crossplane.io/v1alpha1
        kind: DBCluster
        spec:
          forProvider:
            engine: aurora-postgresql
            masterUsername: postgres
            masterUserPasswordSecretRef:
              key: password
            databaseName: postgres
            skipFinalSnapshot: true
            dbClusterParameterGroupNameSelector:
              matchControllerRef: true
              matchLabels:
                engine: aurora-postgresql
            applyImmediately: true
          writeConnectionSecretToRef:
            name: dbzone
            namespace: default
      patches:
        - type: PatchSet
          patchSetName: common-parameters      
        - fromFieldPath: spec.parameters.masterUserSecret.name
          toFieldPath: spec.forProvider.masterUserPasswordSecretRef.name
        - fromFieldPath: spec.parameters.masterUserSecret.namespace
          toFieldPath: spec.forProvider.masterUserPasswordSecretRef.namespace

    - name: dbzoneparametergroup
      base:
        apiVersion: route53.aws.crossplane.io/v1alpha1
        kind: DBClusterParameterGroup
        metadata:
          labels:
            engine: aurora-postgresql
        spec:
          forProvider:
            dbParameterGroupFamily: aurora-postgresql12
            description: "aurora-postgresql-db-parameters"
      patches:
        - type: PatchSet
          patchSetName: common-parameters      

