app:
  name: ""
  extraEnv:
    - name: AUTH0_DOMAIN
      value: ""
  image: ""
  containerPort: 8080
virtualService:
  hosts: []
db:
  name: ""
  sslmode: require
  migration:
    image: ""
    repoURL: ""
    path: ""
strategy:
  canary:
    steps:
      - setWeight: 5
      - pause: {}
      - setWeight: 50
      - pause:
          duration: 60
