{{ if .Values.externalSecrets.aws.secretsManager.serviceAccountName }}
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secrets-store-aws-sm
  namespace: {{ .Values.argocd.namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: "ap-southeast-2"
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.externalSecrets.aws.secretsManager.argocdServiceAccountName }}
---            
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secrets-store-aws-sm
  namespace: telemetry
spec:
  provider:
    aws:
      service: SecretsManager
      region: "ap-southeast-2"
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.externalSecrets.aws.secretsManager.telemetryServiceAccountName }}
---            
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secrets-store-aws-sm
  namespace: app
spec:
  provider:
    aws:
      service: SecretsManager
      region: "ap-southeast-2"
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.externalSecrets.aws.secretsManager.appServiceAccountName }}
{{ end }}