{{ if .Values.externalSecrets.aws.secretsManager.serviceAccountName }}
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secrets-store-aws-sm
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: "ap-southeast-2"
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.externalSecrets.aws.secretsManager.serviceAccountName }}
{{ end }}