apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: rds-svc-pgsql
spec:
  hosts:
  - "github.com"
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS