{{ if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: rds-secret
  namespace: app
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: secrets-store-aws-sm
    kind: SecretStore
  target:
    name: rds
    creationPolicy: Owner
    template:
      data:
        POSTGRES_HOST: "{{ .host | toString }}"
        POSTGRES_PORT: "{{ .port | toString }}"
        POSTGRES_USERNAME: "{{ .username | toString }}"
        POSTGRES_PASSWORD: "{{ .password | toString }}"
  dataFrom:
    - key: "{{ .Values.externalSecrets.rdsSecretName }}"
{{ end }}