---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: rdsclusters.rds.jk8s.io
spec:
  group: rds.jk8s.io
  names:
    kind: RDSCluster
    plural: rdsclusters
  connectionSecretKeys:
    - endpoint
    - username
    - password
    - port
    - db
  versions:
  - name: v1beta1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  region:
                    description: Region for the RDS Cluster
                    type: string       
                    enum: ["ap-southeast-2"]   
                  masterUserSecret:
                    type: object
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                required:
                  - region
            required:
              - parameters
