apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: master-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "{{ .Values.jk8s.apps.repoURL }}"
    targetRevision: "{{ .Values.jk8s.apps.targetRevision }}"
    path: "{{ .Values.jk8s.apps.path }}/master-app"
    helm:
      values: |
        {{ toYaml .Values.jk8s | nindent 8 }}
  destination:
    namespace: {{ .Release.Namespace }}
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
