argocd:
  namespace: ""

externalSecrets:
  enabled: false
  rdsSecretName: ""
  aws:
    secretsManager:
      argocdServiceAccountName: ""
      telemetryServiceAccountName: ""
      appServiceAccountName: ""

certManager:
  letsEncrypt:
    staging:
      enabled: false
      email: ""
      route53:
        zoneID: ""
    production:
      enabled: false
      email: ""
      route53:
        zoneID: ""

rds:
  host: ""

# Defaults
spec:
  destination:
    server: https://kubernetes.default.svc

