apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-gateway-cert
  namespace: istio-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  secretName: ingress-gateway-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - "*.{{ .Values.dns.fqdn }}"
    - "{{ .Values.dns.fqdn }}"
