apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: telemetry
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: ES_PASSWORD
data:
  ES_USERNAME: ZWxhc3RpYwo=
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-search
spec:
  version: 7.16.2
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
  transport:
    tls:
      subjectAltNames:
        - dns: elastic-search-es-default
