apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: jaeger-es-secret
  namespace: telemetry
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secrets-store-aws-sm
    kind: SecretStore
  target:
    name: jaeger-es
    creationPolicy: Owner
    template:
      # multiline string
      config: |
        datasources:
        - name: Graphite
          type: graphite
          access: proxy
          url: http://localhost:8080
          password: "{{ .password | toString }}" # <-- convert []byte to string
          user: "{{ .username | toString }}"         # <-- convert []byte to string

      # data:
      #   ES_USERNAME: "{{ .username }}"
      #   ES_PASSWORD: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: "{{ .Values.jaeger.storage.es.credentialsSecretName }}"
        property: username
    - secretKey: password
      remoteRef:
        key: "{{ .Values.jaeger.storage.es.credentialsSecretName }}"
        property: password
