apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-tracing
spec:
  strategy: streaming
  collector:
    options:
      kafka:
        producer:
          topic: jaeger-spans
          brokers: telemetry-kafka:9092
  ingester:
    options:
      kafka:
        consumer:
          topic: jaeger-spans
          brokers: telemetry-kafka:9092
      ingester:
        deadlockInterval: 0
  storage:
    {{ if .Values.jaeger.storage.es.enabled }}
    type: elasticsearch
    options:
      es:
        server-urls: "{{ .Values.jaeger.storage.es.url }}"
    {{ end }}
    {{ if .Values.jaeger.storage.inMemory.enabled }}
    storage:
      type: memory
      options:
        memory:
          max-traces: 100000    
    {{ end }}
