apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: jaeger-es-secret
  namespace: telemetry
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secrets-store-aws-sm
    kind: SecretStore
  target:
    name: jaeger-es
    creationPolicy: Owner
    template:
      data:
        ES_USERNAME: "{{ .username | toString }}"
        ES_PASSWORD: "{{ .password | toString }}"
  data:
    - secretKey: username
      remoteRef:
        key: "{{ .Values.jaeger.storage.es.credentialsSecretName }}"
        property: username
    - secretKey: password
      remoteRef:
        key: "{{ .Values.jaeger.storage.es.credentialsSecretName }}"
        property: password
