apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-tracing
spec:
  strategy: streaming
  collector:
    options:
      kafka:
        producer:
          topic: jaeger-spans
          brokers: telemetry-kafka:9092
  ingester:
    options:
      kafka:
        consumer:
          topic: jaeger-spans
          brokers: telemetry-kafka:9092
      ingester:
        deadlockInterval: 0
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://elastic-search-es-http.telemetry.svc:9200
        tls:
          ca: /es/certificates/ca.crt
    secretName: elastic-credentials
  volumeMounts:
    - name: certificates
      mountPath: /es/certificates/
      readOnly: true
  volumes:
    - name: certificates
      secret:
        secretName: elastic-search-es-http-certs-public
