apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telmetry-kafka
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kafka
    targetRevision: "14.8.1"
    helm:
      releaseName: telemetry-kafka
  destination:
    namespace: telemetry
    server: "{{ .Values.spec.destination.server }}"
  syncPolicy:
    automated:
      prune: true
