apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: {{ Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: base
    targetRevision: "1.12.1"
    helm:
      releaseName: istio-base

  destination:
    namespace: istio-system
    server: "{{ .Values.spec.destination.server }}"

  syncPolicy:
    automated:
      prune: true
