apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jaeger-vs
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  hosts:
    - "jaeger.{{ .Values.dns.fqdn }}"
  gateways:
    - istio-ingress/ingress-gateway
  http:
    - route:
        - destination:
            host: jaeger-tracing-query
            port:
              number: 16686
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: jaeger
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  host: jaeger-tracing-query
  trafficPolicy:
    tls:
      mode: DISABLE
---

