apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: jaeger-es-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: secrets-store-aws-sm
    kind: SecretStore
  target:
    name: jaeger-es
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        ES_USERNAME: "{{ "{{ .username | toString }}" }}"
        ES_PASSWORD: "{{ "{{ .password | toString }}" }}"
  data:
    - secretKey: password
      remoteRef:
        key: "{{ .Values.jaeger.storage.es.credentialsSecretName }}"
        property: password
    - secretKey: username
      remoteRef:
        key: "{{ .Values.jaeger.storage.es.credentialsSecretName }}"
        property: username
