apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-sql
spec:
  package: "crossplane/provider-sql:master"
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  defaultDatabase: postgres
  credentials:
    source: PostgreSQLConnectionSecret
    connectionSecretRef:
      namespace: crossplane
      name: rds