apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: provider-sql-debug-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  args:
    - --debug
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-sql
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  package: "crossplane/provider-sql:master"
  controllerConfigRef:
    name: provider-sql-debug-config
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  defaultDatabase: postgres
  credentials:
    source: PostgreSQLConnectionSecret
    connectionSecretRef:
      namespace: crossplane
      name: rds
