{{ $server := .Values.spec.destination.server  }}
{{ $fqdn := .Values.dns.fqdn }}
{{ if .Values.dns.externalDNS }}
{{ $zoneID := .Values.dns.externalDNS.zoneID }}
{{ else }}
{{ $zoneID := "" }}
{{ end }}
{{ $argocdNamespace := .Values.argocd.namespace }}
{{ range .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .name }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "{{ .repoURL }}"
    {{- if .targetRevision }}
    targetRevision: "{{ .targetRevision }}"
    {{- end }}
    {{- if .path }}
    path: "{{ .path }}"
    {{- end }}
    {{- if .chart }}
    chart: "{{ .chart }}"
    {{- end }}
    helm:
      parameters:
        - name: fqdn
          value: "{{ $fqdn }}"
        - name: zoneID
          value: "{{ $zoneID }}"
        - name: argocd.namespace
          value: "{{ $argocdNamespace }}"
  destination:
    namespace: "app"
    server: "{{ $server }}"
  syncPolicy:
    automated:
      prune: true
{{ end }}