{{ if .Values.secrets.externalSecrets.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    istio-injection: disabled
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  project: default
  source:
    repoURL: {{ .Values.repository.repoURL }}
    targetRevision: {{ .Values.repository.targetRevision }}
    path: "{{ .Values.repository.appsPath }}/external-secrets"
    helm:
      parameters:
        - name: enabled
          value: "{{ .Values.secrets.externalSecrets.enabled }}"
        - name: rdsSecretName
          value: "{{ .Values.secrets.externalSecrets.rdsSecretName }}"
        - name: aws.secretsManager.argocdServiceAccountName
          value: "{{ .Values.secrets.externalSecrets.aws.secretsManager.argocdServiceAccountName }}"
        - name: aws.secretsManager.jaegerServiceAccountName
          value: "{{ .Values.secrets.externalSecrets.aws.secretsManager.jaegerServiceAccountName }}"
        - name: aws.secretsManager.appServiceAccountName
          value: "{{ .Values.secrets.externalSecrets.aws.secretsManager.appServiceAccountName }}"
        - name: aws.secretsManager.crossplaneServiceAccountName
          value: "{{ .Values.secrets.externalSecrets.aws.secretsManager.crossplaneServiceAccountName }}"
  destination:
    namespace: external-secrets
    server: "{{ .Values.spec.destination.server }}"
  syncPolicy:
    automated:
      prune: true
{{ end }}
