---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.platformApp.repoURL }}
    targetRevision: {{ .Values.platformApp.targetRevision }}
    path: "{{ .Values.platformApp.appsPath }}/istio"
    helm:
      parameters:
        - name: serviceEntries.rds.host
          value: "{{ .Values.rds.host }}"
        - name: argocd.namespace
          value: "{{ .Values.argocd.namespace }}"

  destination:
    namespace: istio-system
    server: "{{ .Values.spec.destination.server }}"

  syncPolicy:
    automated:
      prune: true
