apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress-chart
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: "~1.12.1"
    helm:
      releaseName: istio-ingress
  destination:
    namespace: istio-ingress
    server: "{{ .Values.spec.destination.server }}"
  syncPolicy:
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repository.repoURL }}
    targetRevision: {{ .Values.repository.targetRevision }}
    path: "{{ .Values.repository.appsPath }}/istio-ingress"
    helm:
      parameters:
        - name: dns.fqdn
          value: "{{ .Values.dns.fqdn }}"
        - name: argocd.namespace
          value: "{{ .Values.argocd.namespace }}"
        - name: argocd.fqdn
          value: "argocd.{{ .Values.dns.fqdn }}"
        - name: argocd.service
          value: "{{ .Values.helm.releaseName }}-argocd-server"
  destination:
    namespace: istio-ingress
    server: "{{ .Values.spec.destination.server }}"
  syncPolicy:
    automated:
      prune: true
