apiVersion: v1
kind: Namespace
metadata:
  name: kiali
  labels:
    istio-injection: disabled
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "{{ .Values.repository.repoURL }}"
    targetRevision: "{{ .Values.repository.targetRevision }}"
    path: "{{ .Values.repository.appsPath }}/kiali"
    helm:
      parameters:
        - name: dns.fqdn
          value: "{{ .Values.dns.fqdn }}"

  destination:
    namespace: kiali
    server: "{{ .Values.spec.destination.server }}"

  syncPolicy:
    automated:
      prune: true
