apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: "{{ .Values.repository.url }}"
    targetRevision: "{{ .Values.repository.targetRevision }}"
    path: "{{ .Values.repository.appsPath }}/prometheus"
    helm:
      parameters:
        - name: dns.fqdn
          value: "{{ .Values.dns.fqdn }}"
        - name: argocd.namespace
          value: "{{ .Values.argocd.namespace }}"

  destination:
    namespace: telemetry
    server: "{{ .Values.spec.destination.server }}"

  syncPolicy:
    automated:
      prune: true
